### ISSUE TITLE
Scrollable in separate.

### ISSUE THREAD

**Issue by tohman** [blackberry/WebWorks-API-Docs#114]
Having two sides of a page, (left is an API index and right is content), be scrollable in separate would be convenient.

User Case: When API list would become longer, then when user interested to explore some category, 'User Interface' for instance, after each selection he supposed to scroll back in the index to where he were.

**Comment by tneil** [comment]
This is also being discussed in the following issue: https://github.com/blackberry/WebWorks-API-Docs/issues/78
