### ISSUE TITLE
blackberry.app.event.onExit is not documented

### ISSUE THREAD

**Issue by gtanner** [blackberry/WebWorks-API-Docs#141]
Still defined in the webworks code:
https://github.com/blackberry/WebWorks/blob/master/api/app/src/blackberry/app/event/AppEventNamespace.java#L34

Should this be removed from webworks, or should this be documented?

**Comment by TowleT** [comment]
Not supported on PlayBook

**Comment by cdelcol** [comment]
Merged per commit 233d3fb
