### ISSUE TITLE
blackberry.utils.URL methods only show up for playbook

### ISSUE THREAD

**Issue by gtanner** [blackberry/WebWorks-API-Docs#146]
With the dropdown selected for any other platform the page is empty.

**Comment by gtanner** [comment]
See: 
https://github.com/blackberry/WebWorks/blob/master/api/utils/src/blackberry/utils/ParseURLFunction.java

**Comment by gtanner** [comment]
Docs say port on the URL object is a string.
Should be an int:
https://github.com/blackberry/WebWorks-TabletOS/blob/master/js_api/BlackBerry_Utilities/js/common/utilities_ns.js#L84
and
https://github.com/blackberry/WebWorks/blob/master/api/utils/src/blackberry/utils/URL/URLObject.java#L76

**Comment by tohman** [comment]
URL methods appears only for Playbook can't be reproduced when compiled with new templates/plugin.
