### ISSUE TITLE
blackberry.utils.generateUniqueID wrong casing

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks-API-Docs#148]
In the docs it says blackberry.utils.generateUniqueID when it should be blackberry.utils.generateUniqueId... Notice the lower case "d" instead of the "D" on ID

**Comment by gtanner** [comment]
Dupe of:
https://github.com/blackberry/WebWorks-API-Docs/pull/145

beat you to it Tim ;)

**Comment by tneil** [comment]
Awesome... 

See Pull request https://github.com/blackberry/WebWorks-API-Docs/pull/145
