### ISSUE TITLE
Filter Drop Down does not remember previous setting

### ISSUE THREAD

**Issue by jeffheifetz** [blackberry/WebWorks-API-Docs#15]
Select an platform (e.g. BlackBerry PlayBook) from drop down list and select an item (e.g. Acceleration), the drop down list and when the page opens the drop down list is reset to “Show All APIs”.

**Comment by tneil** [comment]
We should be able to save this in cookies like we are saving the TOC/object list settings.

**Comment by tneil** [comment]
This is now fixed in the following pull request https://github.com/blackberry/WebWorks-API-Docs/pull/27
