### ISSUE TITLE
Device Motion Event Corrections

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks-API-Docs#150]
After talking with the testing group, the following properties should be REMOVED from the HTML5 device motion event documentation
- acceleration
- rotationRate

We only support the following on HTML5 Device Motion:
- accelerationIncludingGravity
- interval

We should also update the text at the top of the Device Motion Event page to not indicate that the hardware doesn't have a Gyroscope, but simply that we only currently support data from the Accelerometer and not the Gyroscope.

We should also drop the RotationRate object entirely from the docs

**Comment by jeffheifetz** [comment]
TowleT did some of these changes in pull #142, I'll cross reference this issue there as well
