### ISSUE TITLE
BlackBerry PlayBook Filter has some issues on IE

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks-API-Docs#162]
On IE, applying the BlackBerry PlayBook filter doesn't remove Menu and Menu Item from the TOC..

**Comment by cdelcol** [comment]
in the server.js file, there is a function getDesiredElements that calls element.hasAttributes(attributeName). it is labeled as a way for IE6.0 to support the functionality, but doesn't seem to work in IE 8.0 (at least).

Likely, we should revisit the templates and introduce jQuery for the selectors. We probably have additional issues elsewhere.

**Comment by tneil** [comment]
ok.. we'll probably have to deal with IE 6 separately and add some logic to only use that logic for IE6

**Comment by marek** [comment]
might be the other way around. IE8 could be running in compatibility mode?
http://www.quirksmode.org/dom/w3c_core.html

says support for the attribute is IE8 and up

**Comment by marek** [comment]
fixed the issue in ababut/WebWorks-API-Docs@c16fee77efcd35814c45e067b0c4c6c1718c76fe

**Comment by cdelcol** [comment]
Merged per commit 233d3fb
