### ISSUE TITLE
Camera is shown to support BB5, BB6

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks-API-Docs#164]
Camera API shows that BB5 and BB6 are supported in the expanded table.  We don't yet support the camera API on these platforms.

**Comment by ababut** [comment]
Issue is still present post-Delta merge. The BB5.0+ tags were removed from blackberry_invoke_CameraArguments.js, which was not the correct place. CameraArguments is BB5.0+ compatible.

They should be removed from https://github.com/blackberry/WebWorks-API-Docs/blob/delta/api/blackberry_media_camera.js.

You can microphone as an example: https://github.com/blackberry/WebWorks-API-Docs/blob/delta/api/blackberry_media_microphone.js

**Comment by ababut** [comment]
Fixed through PR #180.
