### ISSUE TITLE
Feature and Permission Titles should be left justified

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks-API-Docs#170]
We should make our "Feature Elements" and "Permissions Elements" be left justified instead of centered to be consistent with out other titles

**Comment by tneil** [comment]
Making the titles be the same color as the text below them but still keeping them bold should likely also help them seem as though they are part of the "Configuration Document Settings" and not look like a new section

**Comment by ababut** [comment]
Fixed through PR #180.
