### ISSUE TITLE
Canvas Wording could be re-done

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks-API-Docs#171]
Current top of page description for canvas looks like it is point form and was never finished

The canvas tag is used to display graphics. 
The canvas tag is only a container for graphics, you must use a script to actually paint graphics.
The canvas tag is new in HTML5.
Any text inside the between <canvas> and </canvas> will be displayed in browsers that does not support the canvas element.

**Comment by ababut** [comment]
Fixed through PR #180.
