### ISSUE TITLE
HTML5 Local Storage Shows support for BB5

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks-API-Docs#172]
HTML5 Local Storage shows that it supports BB5.. when it should be showing that it supports PlayBook and not the others.

**Comment by cdelcol** [comment]
I suspect that this was fixed yesterday through a merge from master branch.

**Comment by tneil** [comment]
Issue is now resloved

**Comment by tneil** [comment]
I was too quick on the trigger finger.. still have to verify
