### ISSUE TITLE
Filter Expressions don't tell developers what operators are available

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks-API-Docs#176]
Both on the blackberry.find.FilterExpression and the blackberry.phone.Find.FilterExpression we don't document what operators can be used in the operator field or mention that regular expressions can be used for strings in the rightField.

**Comment by tneil** [comment]
Also in the Properties area there's only a description for **negate** for both phone.Find.FilterExpression and find.FilterExpression

**Comment by ababut** [comment]
Fix is integrated into the delta branch. Please keep defect open until it's also merged into Epsilon.
