### ISSUE TITLE
Several files appear as namespaces and should be classes

### ISSUE THREAD

**Issue by cpinzon** [blackberry/WebWorks-API-Docs#19]
The following files need to be changed to use @class and @constructor, as they are instances and contain more than just static members:

blackberry.io.file.FlireProperties
blackberry.phone.PhoneLogs.CallLog
blackberry.phone.Phone.Call
blackberry.push.Data
blackberry.menu.MenuItem
blackberry.identity.Service

Please add if you find more

**Comment by marek** [comment]
These are returned by functions and cannot be created by the user so they are fine:
blackberry.io.file.FileProperties
blackberry.phone.PhoneLogs.CallLog
blackberry.phone.Phone.Call
blackberry.push.Data
blackberry.identity.Service

blackberry.menu.MenuItem is fixed

**Comment by cpinzon** [comment]
Thanks dude.
