### ISSUE TITLE
Need to port genDoc.bat file to Mac-friendly version

### ISSUE THREAD

**Issue by ababut** [blackberry/WebWorks-API-Docs#204]
We need either a Mac-compatible equivalent of genDoc.bat or a platform independent version such as an Ant script to allow Mac/Linux users to build the docs with the least number of manual steps possible.

**Comment by tneil** [comment]
See Nukul's Issue #208

**Comment by ababut** [comment]
This issue was opened to track that. It should've been referenced from the commit message of the fix.

**Comment by cdelcol** [comment]
merged as part of issue #208
