### ISSUE TITLE
Doc update: Contact property categories is an array

### ISSUE THREAD

**Issue by purdrew** [blackberry/WebWorks-API-Docs#223]
The WebWorks documentation documents the categories property of a blackberry.pim.Contact object to be a String when in fact it is an Array of Strings:

http://www.blackberry.com/developers/docs/webworks/api/blackberry.pim.Contact.html﻿

**Comment by tneil** [comment]
This must have been missed when we transferred over to jsDocs

**Comment by jeffheifetz** [comment]
This is also true for Tasks http://www.blackberry.com/developers/docs/webworks/api/blackberry.pim.Task.html#categories and possibly all PIM items

**Comment by tneil** [comment]
Ok...I'm taking a look into it

**Comment by tneil** [comment]
Fixes on the way  

https://github.com/blackberry-webworks/WebWorks-API-Docs/pull/4
