### ISSUE TITLE
Typo: Phone.inActiveCall docs

### ISSUE THREAD

**Issue by brentlintner** [blackberry/WebWorks-API-Docs#224]
The Phone.inActiveCall function definition is listed as returning a void type...

```
static void inActiveCall()
```

...while the description and examples below it list as returning a Boolean (which is correct).

I believe the issue is the definition lacking a @type line around here: (?)
https://github.com/blackberry/WebWorks-API-Docs/blob/master/api/blackberry_phone_Phone.js#L433

I would of submitted a pull request, but I was not sure.

Cheers,

**Comment by tneil** [comment]
On it...

**Comment by tneil** [comment]
Issue was that the @returns tag was on the same line as the description

**Comment by tneil** [comment]
Pull request pending https://github.com/blackberry-webworks/WebWorks-API-Docs/pull/2
