### ISSUE TITLE
Example goes against URI as opposed to procedural call

### ISSUE THREAD

**Issue by dansilivestru** [blackberry/WebWorks-API-Docs#231]
In this documentation example we show a call to the URI service. We should be showing an example of how to call the JS procedural API:

https://github.com/blackberry/WebWorks-API-Docs/blob/master/api/blackberry_identity.js#L48-76

**Comment by tneil** [comment]
That example looks correct... It is showing how to call the URI based "get" call on the URI documentation

**Comment by tneil** [comment]
It can be seen here in the production documents
http://www.blackberry.com/developers/docs/webworks/api/blackberry.identity.html#.get

**Comment by tneil** [comment]
Although it looks like the "Code Example(s)" area at the very bottom of the page should be moved up to the procedural area

It could probably be broken up into a code example for each of the procedural APIs instead of one generic code example

**Comment by dansilivestru** [comment]
Ah, good point. I was filtering by "BlackBerry PlayBook" in the docs and it only showed the URI get example, so it seemed wrong to me.

**Comment by tneil** [comment]
Yeah.. if that code example that's right at the bottom was split up and added to each of the procedural APIs then it wouldn't be as hidden

The only other thing that shows up when you apply the filter is the Procedural API property for PIN

**Comment by tneil** [comment]
Update pending here

https://github.com/blackberry-webworks/WebWorks-API-Docs/pull/3
