### ISSUE TITLE
setHomeScreenIcon setHomeScreenName support incorrect

### ISSUE THREAD

**Issue by purdrew** [blackberry/WebWorks-API-Docs#232]
blackberry.app.setHomeScreenIcon and blackberry.app.setHomeScreenName both list "BlackBerry OS 5.0+" as the only supported platform but text in the "Description" and "Returns" areas for both mention the PlayBook.

**Comment by tneil** [comment]
Thanks Drew,

I've attached a pull request that should fix this in the smartphone branch.  Well try and get this into the next update of the docs

https://github.com/blackberry/WebWorks-API-Docs/pull/233
