### ISSUE TITLE
blackberry.app.isForeground is not documented

### ISSUE THREAD

**Issue by brentlintner** [blackberry/WebWorks-API-Docs#235]
The method seems to be part of the WebWorks source but is not listed in the docs.

https://github.com/blackberry/WebWorks/blob/master/api/app/src/main/java/blackberry/app/AppNamespace.java#L106-108

There also seems to be a line for this in the docs that is commented out:

https://github.com/blackberry/WebWorks-API-Docs/blob/master/api/blackberry_app.js#L159

Is this still an official API property?

**Comment by tneil** [comment]
Hi Brent... Yup it is on the Smartphone but not the Tablet.. I'll make the change

**Comment by tneil** [comment]
Changes are waiting in progress in the blackberry-webworks organization

https://github.com/blackberry-webworks/WebWorks-API-Docs/pull/1
