### ISSUE TITLE
Incorrect code example for SystemEvent docs page (BB and Tablet)

### ISSUE THREAD

**Issue by brentlintner** [blackberry/WebWorks-API-Docs#240]
There are 2 examples at the bottom of the [SystemEvent docs](http://www.blackberry.com/developers/docs/webworks/api/blackberry.system.event.html) for BB 5/6.

The last one references a "notifyOnBatteryLevelChange" function, which does not seem to fit the functions being documented above.

The same is also true for the opposite. On the Playbook (Tablet) page for SystemEvent, there are 2 examples at the bottom. The 1rst is the onHardwareKey example from the BB 5/6 which does not seem to fit the methods documented above.

**Comment by jeffheifetz** [comment]
Both examples seem fine.

notifyOnBatteryLevelChange calls blackberry.system.event.deviceBatteryLevelChange.

**Comment by jengee** [comment]
Just checked the examples as well and they are correct. It's just unfortunate the names of functions are so close to the parameter names etc which makes it really confusing

**Comment by jeffheifetz** [comment]
Fixed by #301
