### ISSUE TITLE
blackberry.io.file.saveFile && blackberry.io.file.readFile documentation for tablet incorrect

### ISSUE THREAD

**Issue by ndaversa** [blackberry/WebWorks-API-Docs#256]
Both blackberry.io.file.saveFile && blackberry.io.file.readFile exist for tablet, however the documentation states they are not available (http://www.blackberry.com/developers/docs/webworks/api/blackberry.io.file.html).

Implementation evidence can be found here...
https://github.com/blackberry/WebWorks-TabletOS/blob/master/js_api/blackberry.io.file/src/Air/File/src/blackberry/io/file/FileExtension.as

**Comment by tneil** [comment]
They are "officially" not available/supported even though the software has the code...   The main use case scenario was not implemented in the release.. thus we don't support these APIs yet
