### ISSUE TITLE
HTML5 Video and BB6

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks-API-Docs#260]
Currently our API docs specify that BB6 [supports HTML5 video](http://www.blackberry.com/developers/docs/webworks/api/HTMLVideoElement.html) when it doesn't actually support it.

We need to remove the supported on BB6 flag from the API documentation

**Comment by mattlanham** [comment]
What is the alternative method of playing video in a BB6 application using WebWorks?

**Comment by tneil** [comment]
If you have a link that is an rtsp url, it will automatically open itself up in the BlackBerry media player

**Comment by mattlanham** [comment]
Could i do this with a poster image and invoke the browser on click with the URL?

**Comment by tneil** [comment]
That should work

**Comment by tneil** [comment]
This pull request should fix the docs

https://github.com/blackberry-webworks/WebWorks-API-Docs/pull/52

**Comment by RonMen** [comment]
The "Supported Platform(s)" still contain BB OS 6+ and it seems to work on the one hand and doesn't work on the other?

See 1.) https://developer.blackberry.com/html5/apis/htmlvideoelement.html
See 2.) http://supportforums.blackberry.com/t5/Web-and-WebWorks-Development/no-HTML5-video-with-OS-6-0-0-246/td-p/1853171
