### ISSUE TITLE
blackberry.identity.PIN always returns undefined

### ISSUE THREAD

**Issue by mattlanham** [blackberry/WebWorks-API-Docs#273]
I've tried a couple of different methods, and it's always returning undefined, i've also tried the Ajax approach and that also isn't returning the PIN, i've checked and double checked my config ensuring that the following config's are set, but still nothing, to get PUSH working we need access to this somehow...

I've tried this on OS 6.0 and OS 7.0 with the latest version of WebWorks

I've tried

```
$.ajax({
    type: "get",
    url: "http://localhost:8472/blackberry/identity/get",
    success: function(msg){
        alert(msg);
    }
});
```

Also:

```
var pin= blackberry.identity.PIN;
alert(pin);
```

Currently my config contains every feature, and i've ensured the following is there:

```
<feature id="blackberry.identity" required="true" version="1.0.0.0"/>
<rim:permissions>
    <rim:permit>access_shared</rim:permit>
    <rim:permit>record_audio</rim:permit>
    <rim:permit>read_geolocation</rim:permit>
    <rim:permit>use_camera</rim:permit>
    <rim:permit>read_device_identifying_information</rim:permit>
</rim:permissions>
```

Any assistance would be appreciated...

**Comment by tneil** [comment]
Is this in the simulator or the actual device?

**Comment by tneil** [comment]
Also, the &lt;rim:permit&gt; elements are only needed on a PlayBook and the AJAX call is PlayBook only

**Comment by mattlanham** [comment]
This was on device on a OS 7.0 9900 and OS 6.0 8520 (although reports 9300)

**Comment by tneil** [comment]
I just tried out the following code that I built and installed on:

Torch 9800 OS 6.0
Torch 9860 OS 7.0

This code ran fine and retrieved the PIN of the device

**config.xml**

```
<widget xmlns:rim="http://www.blackberry.com/ns/widgets" version="1.0.0" rim:header="RIM-Widget:rim/widget" xmlns="http://www.w3.org/ns/widgets">
  <rim:navigation mode="focus" />
  <name>PIN Test</name>
  <content src="index.htm" />
  <feature id="blackberry.identity" />
</widget>
```

**index.htm**

```
<html>
<head>
    <script type="text/javascript">

        function getPIN() {
            alert(blackberry.identity.PIN);
        }

    </script>
</head>
<body>
    <button onclick="getPIN()">Click Me</button>
</body>
</html>
```

I'm wondering if there is something else causing an error..

**Comment by mattlanham** [comment]
@tneil it seems that another issue i logged is the root cause of this one also : https://github.com/blackberry/WebWorks-API-Docs/issues/274 

If you have an iFrame in your app invoke stops functioning, seems identity also suffers

**Comment by mattlanham** [comment]
Put this in the head and see if it breaks:

```
<script src="http://debug.phonegap.com/target/target-script-min.js#BBTESTCODE"></script>
```

**Comment by mattlanham** [comment]
actually i use this one more, but any iFrame seems to break including advertising service:
    <script src="http://jsconsole.com/remote.js?BBTESTCODE"></script>

**Comment by tneil** [comment]
Ok.. can you please add the iframe issue to the WebWorks repository... this Repo is for the API docs only so I don't want to loose a bug by having it logged here :)

WebWorks repo:
https://github.com/blackberry/WebWorks/issues?sort=created&direction=desc&state=open

**Comment by mattlanham** [comment]
No problem, presume you can just close the 2 off, there's a bug logged and i commented on it before regarding the Invoke stuff, didn't think it would affect identity, wondering now if that's why i'm getting an error on Push also:

https://github.com/blackberry/WebWorks/issues/66

**Comment by tneil** [comment]
cool.. I would suggest just appending onto that existing issue #66
