### ISSUE TITLE
iFrame causes Invoke to stop functioning

### ISSUE THREAD

**Issue by mattlanham** [blackberry/WebWorks-API-Docs#274]
If i include JSConsole, or also in my case the BlackBerry Advertising Service, this prevents invoke from functioning, removing JSConsole, and Advertising service brings this functionality back into the application.

Is there any way around this as we need Invoke, and we also need the Advertising Service?

**Comment by tneil** [comment]
If you could log this in the WebWorks repo that would be great.  I'll close this issue in the Docs repo

WebWorks repo:

https://github.com/blackberry/WebWorks/issues?sort=created&direction=desc&state=open
