### ISSUE TITLE
navigator.geolocation.watchPosition incorrectly claims ripple support

### ISSUE THREAD

**Issue by jeffheifetz** [blackberry/WebWorks-API-Docs#277]
What he ^ said

As referenced on the forums here - http://supportforums.blackberry.com/t5/Web-and-WebWorks-Development/Ripple-does-not-support-watchPosition/td-p/1205359

**Comment by jengee** [comment]
This issue has been resolved in the latest Ripple that came out in late October. navigator.geolocation.watchPosition is indeed supported.
