### ISSUE TITLE
incorrect code snippet for standardAskAsync and customAskAsync methods

### ISSUE THREAD

**Issue by astanley** [blackberry/WebWorks-API-Docs#292]
The code sample displayed for the standardAskAsync and customAskAsync methods on the blackberry.ui.dialog docs page makes reference to an properties

Currently:  blackberry.ui.dialog.LOC_BOTTOM and blackberry.ui.dialog.LOC_CENTER

Should be (no "LOC_" prefix): blackberry.ui.dialog.BOTTOM  and blackberry.ui.dialog.CENTER

**Comment by jeffheifetz** [comment]
Fixed by Pull Request #301
