### ISSUE TITLE
HTML5 localStorage Device Support

### ISSUE THREAD

**Issue by bthornton32** [blackberry/WebWorks-API-Docs#294]
The API docs only show support for local storage on PlayBook and Ripple. I know it works on BlackBerry devices as well. This list and matrix needs to be updated.

**Comment by kwallis** [comment]
Ugh, I'll see what I can do to get this done.

**Comment by bthornton32** [comment]
Thanks Ken - much appreciated.

**Comment by jeffheifetz** [comment]
Please note from issue #172 there is no BB5.0 support

**Comment by jeffheifetz** [comment]
Additionally, please note by issue #248 that BB6.0 support is not 100%
