### ISSUE TITLE
3 FilterExpressions

### ISSUE THREAD

**Issue by marek** [blackberry/WebWorks-API-Docs#41]
We have 3 FilterExpression objects now 

One in:
https://github.com/blackberry/WebWorks-API-Docs/blob/master/api/blackberry_find_FilterExpression.js
'blackberry.find.FilterExpression'

Two in:
https://github.com/blackberry/WebWorks-API-Docs/blob/master/api/blackberry_phone_Find_FilterExpression.js
Both are 'blackberry.phone.Find.FilterExpression'

Isn't the correct namespace for the constructor blackberry.find.FilterExpression ?

**Comment by tneil** [comment]
They are two separate objects.. they are not one and the same.. One is used for the phone.. and the other is for PIM.  I know.. I know... Why?    You don't want to know the answer to that one :)

It's just the way it currently is.

**Comment by jeffheifetz** [comment]
But we should atleast make it so there's only 1 phone_find_filterexpression

**Comment by tneil** [comment]
Agreed
