### ISSUE TITLE
Issue with title header

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks-API-Docs#94]
It looks like with some of the latest updates to the templates, the gradient title header doesn't stretch across the entire width of the document.  This is the silver gradient that displays the topic title.

**Comment by cpinzon** [comment]
Hi tim,

I believed I had fixed it, but it seems that it got lost somewhere... on it right now.

**Comment by cpinzon** [comment]
Fix: https://github.com/blackberry/WebWorks-API-Docs/pull/100

**Comment by tneil** [comment]
Just tested it and it all looks great!!
